/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operacion;

/**
 *
 * @author CBN
 */
public class Distancia extends javax.swing.JFrame {

    /**
     * Creates new form Distancia
     */
    double x1,x2,y1,y2,resultado;
    Operacion op1 =  new Operacion();
    public Distancia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblx1 = new javax.swing.JLabel();
        lblx2 = new javax.swing.JLabel();
        lbly1 = new javax.swing.JLabel();
        lbly2 = new javax.swing.JLabel();
        txtx1 = new javax.swing.JTextField();
        txtx2 = new javax.swing.JTextField();
        txty1 = new javax.swing.JTextField();
        txty2 = new javax.swing.JTextField();
        btcalcular = new javax.swing.JButton();
        lbldistancia = new javax.swing.JLabel();
        lblresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblx1.setText("x1");

        lblx2.setText("x2");

        lbly1.setText("y1");

        lbly2.setText("y2");

        txtx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx1ActionPerformed(evt);
            }
        });

        txtx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtx2ActionPerformed(evt);
            }
        });

        txty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txty1ActionPerformed(evt);
            }
        });

        txty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txty2ActionPerformed(evt);
            }
        });

        btcalcular.setText("calcular");
        btcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalcularActionPerformed(evt);
            }
        });

        lbldistancia.setText("Distancia: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblx1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblx2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbly2)
                    .addComponent(lbly1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtx1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txty1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txty2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtx2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(lbldistancia)
                        .addGap(18, 18, 18)
                        .addComponent(lblresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btcalcular)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblx1)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblx2)
                            .addComponent(txtx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldistancia)
                            .addComponent(lblresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbly1)
                            .addComponent(txty1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbly2)
                            .addComponent(txty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btcalcular)
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx1ActionPerformed

    private void txtx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtx2ActionPerformed

    private void txty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txty1ActionPerformed

    private void txty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txty2ActionPerformed

    private void btcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalcularActionPerformed
        // TODO add your handling code here:
        x1=Double.parseDouble(txtx1.getText());
        x2=Double.parseDouble(txtx2.getText());
        y1=Double.parseDouble(txty1.getText());
        y2=Double.parseDouble(txty2.getText());
        resultado=op1.resoper(x1, x2, y1, y2);
        lblresultado.setText(""+resultado);
        try{
        x1=Double.parseDouble(txtx1.getText());
        x2=Double.parseDouble(txtx2.getText());
        y1=Double.parseDouble(txty1.getText());
        y2=Double.parseDouble(txty2.getText());
        resultado=op1.resoper(x1, x2, y1, y2);
        lblresultado.setText(""+resultado);
        }catch(Exception e){
        lblresultado.setText("faltan campos por llenar");
        
        }
    }//GEN-LAST:event_btcalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcalcular;
    private javax.swing.JLabel lbldistancia;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JLabel lblx1;
    private javax.swing.JLabel lblx2;
    private javax.swing.JLabel lbly1;
    private javax.swing.JLabel lbly2;
    private javax.swing.JTextField txtx1;
    private javax.swing.JTextField txtx2;
    private javax.swing.JTextField txty1;
    private javax.swing.JTextField txty2;
    // End of variables declaration//GEN-END:variables
}
